### ISSUE TITLE
feat: new Format Preserved Format (FPE) FF1 mask

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#1]
Hi,

Tis is a proposal to support new FF1 Mask

```yaml
mask:
  ff1:
    radix: 62
    keyFromEnv: "FF1_ENCRYPTION_KEY"
    tweakField: "tweak"
```
