### ISSUE TITLE
[PROPOSAL] add unixEpoch format in date parser

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#107]
## Problem

Pimo can't trasnform unixEpoch timestamp (1647512434)  to a date format (Thu Mar 17 2022 10:20:34 GMT+0000).

## Solution

add "unixEpoch" parameter in date parser.

```yaml
  - selector:
      jsonpath: "date"
    mask:
      dateParser:
        inputFormat: "unixEpoch"
        outputFormat: "01/02/06"
```

transform input 

```json
{
  "date": 1647512434
}
```

to output

```json
{
  "date": "17/03/22"
}
```

unixEpoch can be use as outputFormat argument

```yaml
  - selector:
      jsonpath: "date"
    mask:
      dateParser:
        inputFormat: "01/02/06"
        outputFormat:  "unixEpoch"
```
