### ISSUE TITLE
[BUG] use of fromCache after a mask which causes a change in the type of the value

### ISSUE THREAD

**Issue by giraud10** [CGI-FR/PIMO#109]
When you have a field with a calculated value the `fromCache` mask does not work anymore.   

Input file : 
```json
{"sexe": 2.25}
```
------------------
Below are examples of `masking.yml` files where `fromCache` does not work :
```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "sexe"
    masks:
      - constant: 2
      - fromCache: "cacheSex"

caches:
  cacheSex:
    unique: true
    reverse: true
```
-------------------
``` yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "sexe"
    masks:
      - template : "{{ round ( toString .sexe) 0  }}"
      - fromjson: "sexe"
      - fromCache: "cacheSex"
     
caches:
  cacheSex :
    unique: true
    reverse:  true
```
---------------------
Cache file `cacheSex.jsonl`: 
```jsonl
{ "key": "M", "value" : 2}
{ "key": "F", "value" : 1}
``` 
-------------------
```console
pimo --load-cache cacheSex=cacheSex.json -c masking.yml < input.json
```
-------------------
Output file : 
```json
{"sexe": "M"}
```

**Comment by giraud10** [comment]
In input i have :
```jsonl
{"year": 1199747258.18}
```

I want in output:
```jsonl
{"year": 2008}
```

My `masking.yml` file,
```yaml
- selector:
      jsonpath: "year"
    masks:
      - template: "{{round (toString .year) 0 }}"
      - fromjson: "year"
      - dateParser:
          inputFormat: "unixEpoch"
          outputFormat: "2006"
```

```console
panic: interface conversion: model.Entry is float64, not json.Number
```

same problem with `dateParser`
