### ISSUE TITLE
feat(template) : access to context in nested arrays

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#11]
## I want to be able to modify a value in nested arrays by referencing the current value with a template mask.

**`data.jsonl`**
```json
{"elements":[{"persons":[{"name":"bob"},{"name":"john"}]}]}
```

**Expected**
```console
$ pimo <data.jsonl

{"elements":[{"persons":[{"name":"BOB"},{"name":"JOHN"}]}]}
```

#### Using the same path as the selector

This will refer to a field that does not exist `{"elements":{"persons":{"name":"bob"}}}`, and generate an error.

**`masking.yml`**
```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "elements.persons.name"
    mask:
      # this go template syntax refer to a field that is not in a nested array
      template: "{{upper .elements.persons.name}}"
```

**Result**
```console
$ pimo <data.jsonl

template: template:1:17: executing "template" at <.elements.persons.name>: can't evaluate field persons in type model.Entry
```

#### Using go template syntax to access elements in array

This will always use the elements of index 0, and will only give the expected result for the first element `bob`.

**`masking.yml`**
```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "elements.persons.name"
    mask:
      # this go template syntax refer to a single value of index (0;0) 
      template: "{{upper (index (index .elements 0).persons 0).name}}"
```

**Result**
```console
$ pimo <data.jsonl

{"elements":[{"persons":[{"name":"BOB"},{"name":"BOB"}]}]}
```

**Comment by adrienaury** [comment]
### Proposed solution

Create a special context variable that refer to the **current** value.

 **masking.yml**
```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "elements.persons.name"
    mask:
      template: "{{upper .CURRENT}}"
```

 **Result**
```console
$ pimo <data.jsonl

{"elements":[{"persons":[{"name":"BOB"}]}]}
```

**Comment by adrienaury** [comment]
@youen comments concerning the proposed solution ?

**Comment by adrienaury** [comment]
### A better solution

This solution address most of the use case around nested arrays.

 **`data.jsonl`**
```json
{"organizations":[{"domain":"company.com","persons":[{"name":"leona","surname":"miller","email":""},{"name":"joe","surname":"davis","email":""}]}]}
```

 **`masking.yml`**
```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "organizations.persons"
    mask:
      pipe:
        inject-parent: "_"
        masking:
          - selector:
              jsonpath: "name"
            mask:
              template: "{{ title .name }}"
          - selector:
              jsonpath: "surname"
            mask:
              template: "{{ title .surname }}"
          - selector:
              jsonpath: "email"
            mask:
              template: "{{ lower .name }}.{{ lower .surname }}@{{ ._.domain }}"
```

 **Result**
```console
$ pimo <data.jsonl

{"organizations":[{"domain":"company.com","persons":[{"name":"Leona","surname":"Miller","email":"leona.miller@company.com"},{"name":"Joe","surname":"Davis","email":"joe.davis@company.com"}]}]}
```
