### ISSUE TITLE
[BUG] template over slice of map cause error

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#114]
pimo version :  1.12.1

This venom test fail

```yaml
  - name: template with range over slice of map
    steps:
      - script: rm -f masking.yml
      - script: |-
          cat > masking.yml <<EOF
          version: "1"
          masking:
            - selector:
                jsonpath: "CLE_V2_DOCUMENT.LIEN"
              mask :
                template: '[[if eq (int .CLE_V2_DOCUMENT.ID_LOC) (int "1") ]]OB=2016001-0/0 PDF[[else if has (int .CLE_V2_DOCUMENT.ID_LOC) (list 10 12 13 14 15 16 17 18 19 20 21 22) ]]29Z3lvv1r3a90ULQmGfiwddPPWq5W4fd[[else]][[.CLE_V2_DOCUMENT.LIEN]][[end]]'
          EOF
      - script: sed -i  "s/\[\[/\{\{/g"  masking.yml
      - script: sed -i  "s/\]\]/\}\}/g"  masking.yml
      - script: |-
          pimo <<EOF
          {"CODE_FAMILLE":"DOCDE","ID_DN":"1320000522255","NOM_CLE":"idRCI","TYPE_DOC":"AEMP","VALEUR_CLE":"1003468703","CLE_V2_DOCUMENT":[{"CODE_ERREUR_INTEGRATION":"","DATE_CREATION":"2020-03-11T19:42:12+01:00","DATE_MODIFICATION":null,"ID_DN":"1320000522255","ID_LOC":1,"LIEN":"OB=2020025-328/2272 PDF","METAS":"{\"idDoc\":1320000522255,\"cDoc\":\"AEMP\",\"idGED\":\"22003111942005580020370050331894\",\"cReg\":\"025\",\"taill\":204,\"tFlux\":\"UGUD\",\"idDE\":\"3997529\",\"dtArc\":\"20200310\",\"dtArr\":\"20200310\",\"dtDif\":\"20200310\",\"icon\":\"3997529\",\"cle\":\"R\",\"nbPag\":3,\"sTypo\":\"407\",\"idRCI\":1003468703,\"cCont\":1,\"cStaW\":3,\"caRec\":\"R1\",\"cFac\":\"W\",\"dses\":\"20200310\",\"dStaW\":\"20200311\",\"hDiff\":\"12:04:22\",\"typo\":\"40\",\"cAgen\":\"02012\",\"dtTrt\":\"20200311\",\"iGedO\":\"22003102003101204234489627952860\",\"corb\":\"TORECORD\",\"cSite\":\"25906\"}","STATUT_DN":2,"SUPPRIME":0,"TYPE_DOC":"AEMP","TYPE_MIME":"application/pdf"}]}
          EOF
        assertions:
          - result.code ShouldEqual 0
          - result.systemerr ShouldBeEmpty
          - result.systemoutjson.CLE_V2_DOCUMENT.0.LIEN ShouldEqual OB=2016001-0/0 PDF
```

```console
       • template-with-range-over-slice-of-map FAILURE
Testcase "template with range over slice of map", step #4: Assertion "result.code ShouldEqual 0" failed. expected: 0  got: 4 (test/workspace/masking_template.yml:75)
Testcase "template with range over slice of map", step #4: Assertion "result.systemerr ShouldBeEmpty" failed. expected '9:09PM ERR Cannot execute pipeline error="Pipeline didn't complete run: template: template:1:29: executing \"template\" at <.CLE_V2_DOCUMENT.ID_LOC>: can't evaluate field ID_LOC in type model.Entry" config=masking.yml duration="550.823µs" input-line=1 output-line=1' to be empty but it wasn't (test/workspace/masking_template.yml:76)
Testcase "template with range over slice of map", step #4: Assertion "result.systemoutjson.CLE_V2_DOCUMENT.0.LIEN ShouldEqual OB=2016001-0/0 PDF" failed. expected: OB=2016001-0/0 PDF  got: <nil> (test/workspace/masking_template.yml:77)
ERROR running target 'test-int': in step 4: executing command: exit status 2
```

**Comment by giraud10** [comment]
```yaml
version: "1"
masking:
  - selector:
      jsonpath: "CLE_V2_DOCUMENT"
    mask:
      pipe:
        masking:
          - selector:
              jsonpath: "LIEN"
            mask :
              template: '{{if eq (int .ID_LOC) (int "1") }}OB=2016001-0/0 PDF{{else if has (int .ID_LOC) (list 10 12 13 14 15 16 17 18 19 20 21 22) }}29Z3lvv1r3a90ULQmGfiwddPPWq5W4fd{{else}}{{.LIEN}}{{end}}'
```

**Comment by giraud10** [comment]
I found an alternative to the problem but I think this solution is less obvious for the user.

```json
{"field1": "cat", "field2": "dog", "field3": [{"A":"horse", "B":"fish", "C":"monkey"}]}
```

If user wants to mask a value by the value of **field1** or **field2** then he must use the *.root* prefix (`template: {{.root.field1}}`).
Or if he wants to hide a value by the value of **one of the fields of field3** (A, B or C) then it must use the prefix *.parent* (`template: {{.parent.A}}`).

Here are some examples of use,

- Example 1:
``` yml
version: "1"
masking:
  - selector:
      jsonpath: "CLE_V2_DOCUMENT.LIEN"
    mask :
      template: '{{if eq (int .parent.ID_LOC) (int "1") }}OB=2016001-0/0 PDF{{else if has (int .parent.ID_LOC) (list 10 12 13 14 15 16 17 18 19 20 21 22) }}29Z3lvv1r3a90ULQmGfiwddPPWq5W4fd{{else}}{{.parent.LIEN}}{{end}}'
```
input:
```json
{"CODE_FAMILLE":"DOCDE","ID_DN":"1320000522255","NOM_CLE":"idRCI","TYPE_DOC":"AEMP","VALEUR_CLE":"1003468703","CLE_V2_DOCUMENT":[{"ID_LOC":1,"LIEN":"OB=2020025-328/2272 PDF"},{"ID_LOC":12,"LIEN":"OB=2020025-328/2272 PDF"}]}
```

- Example 2:
```yml
version: "1"
masking:
  - selector:
      jsonpath: "foo"
    mask:
      template: "{{.root.baz}}"
```
input:
```json
{"baz": "BAZ", "foo": "BAR"}
```

- Example 3:
```yml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "identity.age"
    mask:
      template: "{{.parent.surname}}.{{.parent.name}}@gmail.com"
```
input:
```json
{"town": "Nantes", "identity": {"age": 27, "name":"Jean", "surname": "Bertrand"}}
{"town": "Nantes", "identity": {"age": 58, "name":"Benjamin", "surname": "Martin"}}
{"town": "Rennes", "identity": {"age": 35, "name":"Benjamin", "surname": "Bertrand"}}
{"town": "Rennes", "identity": {"age": 28, "name":"Jean", "surname": "Martin"}}
```

- Example 4:
```yml
version: "1"
masking:
  - selector:
      jsonpath: "foo.bar"
    mask:
      template: "{{.root.test}}"
```
input:
```json
{"test": "BAZ", "foo": [{"bar": "BAR"},{"bar": "BAR"}]}
```
