### ISSUE TITLE
[PROPOSAL] Enrich template functions by YAML definition

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#137]
# Problem

Complex multi steps template can be difficult to read. We need a solution to mutualize data processing formulas in a single configuration element.

# Proposal

- Add a new root section in masking.yml `functions` : 
- Load functions in the template engine (as it is already done for Sprig functions, or NoAccent)

```yaml
version: "1"
functions:
  rangLettre:
    params:
      lettre: string
    code: -|
      return lettre - 'A' + 1;
masking:
  - selector:
      jsonpath: "rang_lettre_J"
    mask:
      template: "{{rangLettre 'J'}}"
```

OR (simpler) :

```yaml
version: "1"
functions: -|
  func rangLettre(lettre) {
    return lettre - 'A' + 1;
  }
masking:
  - selector:
      jsonpath: "rang_lettre_J"
    mask:
      template: "{{rangLettre 'J'}}"
```

## Extends use of function in masks

```yaml
version: "1"
functions: -|
  func anonRIB(rib) {
    ...
    return anonimizedRIB;
  }
masking:
  - selector:
      jsonpath: "RIB"
    mask:
      call: "anonRIB"
```

With params :

```yaml
version: "1"
functions: -|
  func anonRIB(rib) {
    ...
    return anonimizedRIB;
  }
masking:
  - selector:
      jsonpath: "RIB"
    mask:
      call: 
        name: "anonRIB"
        paramsFromContext:
           - "RIB"
```
