### ISSUE TITLE
[BUG] Cache should apply on whole masking item

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#145]
# Example YAML 

```yaml
version: "1"
caches:
  mycache:
    unique: true
masking:
  - selector:
      jsonpath: "test"
    masks:
      - add: "1"
      - constant: "1"
    cache: mycache
```

## Expected

```console
$ pimo --empty-input
1
```

## Actual

```console
$ pimo --empty-input
5:21PM ERR Cannot execute pipeline error="Pipeline didn't complete run: Unique value not found" config=masking.yml duration="598.2µs" input-line=1 output-line=1
```

**Comment by adrienaury** [comment]
# Another example

**`masking.yml`**
```yaml
version: "1"
caches:
  mycache:
    unique: true
masking:
  - selector:
      jsonpath: "test"
    masks:
      - incremental:
          start: 0
          increment: 1
      - template: "#{{.test}}"
    cache: mycache
```

**`data.jsonl`**
```json
{"test":"A"}
{"test":"B"}
{"test":"C"}
```

## Expected

```console
$ pimo --dump-cache mycache=cache.jsonl < data.jsonl
{"test":"#0"}
{"test":"#1"}
{"test":"#2"}
$ cat cache.jsonl
{"key":"A","value":"#0"}
{"key":"B","value":"#1"}
{"key":"C","value":"#2"}
```

## Actual

```console
$ pimo --dump-cache mycache=cache.jsonl < data.jsonl
{"test":"#0"}
{"test":"#1"}
{"test":"#2"}
$ cat cache.jsonl
{"key":"A","value":0}
{"key":0,"value":"#0"}
{"key":"B","value":1}
{"key":1,"value":"#1"}
{"key":"C","value":2}
{"key":2,"value":"#2"}
```
