### ISSUE TITLE
[PROPOSAL] Define masking in a one-liner

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#17]
# One line masking definition

Sometime, when fast iterating in a testing phase, it can be useful to run a pipeline without writing a masking.yml file.

Example

```console
$ echo '{"value": ""}' | pimo --repeat 5 --mask "value=[{fluxUri: 'pimo://nameFR'}]"
{"value": "Aaron"}
{"value": "Abel"}
{"value": "Abel-François"}
{"value": "Abélard"}
{"value": "Abelin"}
```

This is equivalent to the use of the following masking.yml :

```yaml
version: "1"
masking:
  - selector:
      jsonpath: "value"
    mask:
      fluxUri: "pimo://nameFR"
```

The syntax to define masks in one line can be a minified version of YAML, e.g. : https://onlineyamltools.com/minify-yaml
