### ISSUE TITLE
[PROPOSAL] export a pimo play sandbox as venom test

### ISSUE THREAD

**Issue by giraud10** [CGI-FR/PIMO#176]
This is a proposal to add link in the pimo play page to export current status as non regression test in venom test.

We could create a drop-down buttons list on the upper right corner (similar to https://jqplay.org/).
Buttons :

- Share : copy link
- Export as Venom Test

**The venom test is :**

```yaml
name: "test generated  from pimoplay <current url>"
testcases:
- name: declaring cache
  steps:
  - script: rm -f masking.yml
  - script: |-
      cat > masking.yml <<EOF
      <content of the masking cell>
      EOF
  - script: |-
      cat > input.jsonl <<EOF
      <content of the input cell in jsonline format>
      EOF
  - script: |-
      cat > expected.jsonl <<EOF
      <content of the output cell in jsonline format>
      EOF
  - script: |-
      < input.jsonl pimo > result.jsonl
    assertions:
    - result.code ShouldEqual 0
  - script: |-
      diff expected.jsonl result.jsonl
    assertions:
    - result.code ShouldEqual 0
    - result.systemout ShouldBeEmpty
 ```
