### ISSUE TITLE
[PROPOSAL] RandomDate : use "now/currentDate" for minDate or maxDate

### ISSUE THREAD

**Issue by EricSimon** [CGI-FR/PIMO#186]
In order to reuse automatically the masking and to preserve data consitency. It would be interesting to be able to configure minDate or maxDate with the current date (or currentDate +/-i)

**Comment by EricSimon** [comment]
Examples :
```yml
masks: 
      - add: ""
      - randDate:
          dateMin: "2022-01-01T00:00:00Z"
          dateMax: "now"
```

```yml
masks: 
      - add: ""
      - randDate:
          dateMin: "now"
          dateMax: "2022-12-31T00:00:00Z"
```
example with offset (day) :

```yml
masks: 
      - add: ""
      - randDate:
          dateMin: "now - 1"
          dateMax: "now +1"
```
