### ISSUE TITLE
[PROPOSAL] temp property to auto-remove in post-processing

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#19]
# Auto remove

Instead of doing this pattern 

```yaml
version: "1"
masking:
  - selector :
      jsonpath: "temp"
    mask:
      add: "temp_value"
...
<use the field>
...
  - selector:
      jsonpath: "temp"
    mask:
      remove: true
```

Do this 

```yaml
version: "1"
masking:
  - selector :
      jsonpath: "temp"
    temp: true
    mask:
      add: "temp_value"
...
<use the field>
```

**Comment by adrienaury** [comment]
Rename `temp` to `autoremove` for consistency with #20

**Comment by adrienaury** [comment]
Merge #20 and this issue in a single feature :

```yaml
masking:
  - selector :
      jsonpath: "temp"
    if-not-exist: ignore | add | temporary
    mask:
      add: "temp_value"
```

**Comment by adrienaury** [comment]
Update : this feature will not be needed anymore if #21 is implemented

Here is an example

```yaml
  - selector:
      jsonpath: "missing-field"
    masks:
      - add: ""
      - template: "{{substr 2 9 .other_field}}"
```

This solution has the same readability as an `autoadd` or `if-missing` property, and is simpler to implement and reuse the existing mask `add`.

**Comment by adrienaury** [comment]
```yaml
  - selector:
      jsonpath: "field"
    masks:
      - add-temporary: ""
      - template: "{{substr 2 9 .other_field}}"
```

**Comment by adrienaury** [comment]
The first example become 

```yaml
version: "1"
masking:
  - selector :
      jsonpath: "temp"
    mask:
      add-transient: ""
...
<use the field>
```
