### ISSUE TITLE
[PROPOSAL] set seed from command line argument

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#190]
This is a proposal to add argument `--seed` or `-s` to the command line to override the `seed` field in yaml configuration.

for example with that masking file

```yaml
version: "1"
seed : 42
masking:
  - selector:
      jsonpath: "name"
    mask:
      randomChoiceInUri: "pimo://nameFR"
```

`pimo --empty-input` use default seed (42) and generate  
 
```json
{
  "name": "Rolande"
}
```

`pimo --empty-input --seed 41` use the seed `41`  and generate 
 
```json
{
  "name": "Zacharie"
}
```

`pimo --empty-input --seed 0` use the seed `0` generate a random value
 
```json
{
  "name": "<random value>"
}
```

An original idea from @EricSimon  to avoid the use of `sed` in script ;)
