### ISSUE TITLE
[PROPOSAL] Implicit add

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#20]
# Implicit add if the field is missing

Frequently, a field needs to be created, then valorized.

```yaml
version: "1"
masking:
  - selector :
      jsonpath: "gender"
    mask:
      add: ""
  - selector :
      jsonpath: "gender"
    mask:
      randomChoice:
        - "M"
        - "F"
```

This can be simplified with an auto-add feature

```yaml
version: "1"
masking:
  # directly use the valorization mask
  - selector :
      jsonpath: "gender"
    mask:
      randomChoice:
        - "M"
        - "F"
```

Auto-add could also be disabled by default and enabled on demand

```yaml
version: "1"
masking:
  - selector :
      jsonpath: "gender"
    autoadd: true
    mask:
      randomChoice:
        - "M"
        - "F"
```

**Comment by adrienaury** [comment]
Update : this feature will not be needed anymore if #21 is implemented

Here is an example

```yaml
  - selector:
      jsonpath: "missing-field"
    masks:
      - add: ""
      - template: "{{substr 2 9 .other_field}}"
```

This solution has the same readability as an `autoadd` or `if-missing` property, and is simpler to implement and reuse the existing mask `add`.

**Comment by adrienaury** [comment]
The first example become 

```yaml
version: "1"
masking:
  - selector :
      jsonpath: "gender"
    masks:
      - add: ""
      - randomChoice:
          - "M"
          - "F"
```
