### ISSUE TITLE
[PROPOSAL] Chain multiple masks on the same jsonpath

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#21]
# Chain masks on the same jsonpath

A new dedicated mask 

```yaml
  - selector :
      jsonpath: "birthdate"
    mask:
      chain:
        - randDate:
            dateMin: "1960-01-01T00:00:00Z"
            dateMax: "2002-12-31T00:00:00Z"
        - dateParser:
            outputFormat: "2006-01-02"
```

Can be used to split a big YAML file in chunks or to reuse the same YAML on different paths 

```yaml
  - selector :
      jsonpath: "birthdate"
    mask:
      chain:
        definition: mask-date.yaml
  - selector :
      jsonpath: "otherdate"
    mask:
      chain:
        definition: mask-date.yaml
```

**Comment by adrienaury** [comment]
Update

A better semantic in the masking.yml 

```yaml
  - selector:
      jsonpath: "field"
    # masks (with a final S) is an array of mask
    masks:
      - add: ""
      - template: "{{substr 2 9 .cle.siren}}"
      - ff1:
          radix: 10
          keyFromEnv: "FF1_ENCRYPTION_KEY"
    post-masking: remove
```

In the YAML, only one of properties `mask` and `masks` is allowed.
