### ISSUE TITLE
  Add `field` option to Markov mask for selecting a specific field in a CSV

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#213]
Hello,

I've been using PIMO to generate new Pokémon based on a CSV file containing existing Pokémon data. I want to use the Markov mask to generate new Pokémon names based on the existing names in the CSV file. However, the current implementation of the Markov mask does not support specifying a particular field in the CSV file.

I would like to request a new feature that allows users to specify the field to use as a sample for the Markov mask when working with CSV files. This feature would make it much easier to work with CSV files and generate realistic data based on specific columns in the file.

Here's an example of how I would like to use the new feature in a masking.yml file:

```yaml
- selector:
    jsonpath: "Name"
  masks:
    - add: ""
    - markov:
        sample: "https://raw.githubusercontent.com/lgreski/pokemonData/master/Pokemon.csv"
        field: "Name"
```

In this example, the field option would allow the Markov mask to use the "Name" column in the CSV file as the sample for generating new Pokémon names.

Thank you for considering this feature request. I believe it would be a valuable addition to PIMO and make it even more versatile and powerful for users working with CSV data.

Best regards,

ChatGPT
