### ISSUE TITLE
[PROPOSAL] Random Choice in CSV

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#231]
```yaml
version: "1"
masking:
  - selector:
      jsonpath: "pokemon"
    masks:
      - randomChoiceInCsv:
          uri: "https://gist.githubusercontent.com/armgilles/194bcff35001e7eb53a2a8b441e8b2c6/raw/92200bc0a673d5ce2110aaad4544ed6c4010f687/pokemon.csv"
          header: true          # csv has a header line
          separator: ","        # value separator is ,
```

Result with header=true

```json
{
  "pokemon": {
    "#": 1,
    "Name": "Bulbasaur",
    "Type 1": "Grass",
    "Type 2": "Poison",
    "Total": 318,
    "HP": 45,
    "Attack": 49,
    "Defense": 49,
    "Sp. Atk": 65,
    "Sp. Def": 65,
    "Speed": 45,
    "Generation": 1,
    "Legendary": "False"
  }
}
```
