### ISSUE TITLE
[PROPOSAL] findInCSV mask for data masking

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#271]
## Feature Request

**Description:**
I would like to propose the addition of a new `findInCSV` mask to enhance the functionality of data masking in PIMO. This mask will allow users to find and match values in a CSV file based on specific criteria, facilitating more flexible and powerful data masking configurations.

**Example Scenario:**

Consider the following json entry

```json
{ "nom_commune" : "Carquefou" , "code_postal": "44470", "adresse": "9 Boulevard Ampère", "detaille_adresse": ""},
```

and CSV file containing address information:

```csv
id;id_fantoir;numero;rep;nom_voie;code_postal;code_insee;nom_commune;code_insee_ancienne_commune;nom_ancienne_commune;x;y;lon;lat;type_position;alias;nom_ld;libelle_acheminement;nom_afnor;source_position;source_nom_voie;certification_commune;cad_parcelles
44026_2025_00009;;;;44026_2025;9;;Boulevard Ampère;44470;44026;Carquefou;;;359782.18;6698970.6;-1.505103;47.303684;parcelle;;;CARQUEFOU;BOULEVARD AMPERE;commune;commune;0;
44056_0071_00051;;;;44056_0071;51;;Rue  Jules Verne;44130;44056;Fay-de-Bretagne;;;339005.96;6711681.91;-1.789762;47.406914;entrée;;;FAY DE BRETAGNE;RUE JULES VERNE;commune;commune;1;44056000ZY0341
44109_6636_00023;;;;44109_6636;23;;Rue de Pimodan;44100;44109;Nantes;;;352022.72;6687800.33;-1.599017;47.199265;parcelle;;;NANTES;RUE DE PIMODAN;commune;commune;0;
```

Proposed Configuration:

```yaml
version: "1"
masking:
  - selector:
      jsonpath: "detaille_adresse"
    mask:
      findInCSV:
        uri: "path/to/your/file.csv"
        exactMatch:
          csv: "{{.nom_commune}} {{.code_postal}} {{.nom_voie}}"
          entry: "{{.nom_commune}} {{.code_postal}} {{.adresse}}"
        expected: only-one # could be : only-one, at-least-one or many   
        header: true
        separator: ";"
        fieldsPerRecord: 0
        trim: true
```

configuration using the Jaccard similarity metric without an `exactMatch` configuration to handle cases where there might be mistakes in the entry, such as missing accents or differences in letter case:

```yaml
version: "1"
masking:
  - selector:
      jsonpath: "detaille_adresse"
    mask:
      findInCSV:
        uri: "path/to/your/file.csv"
        jaccard:
          csv: "{{.nom_commune}} {{.code_postal}} {{.nom_voie}}"
          entry: "{{.nom_commune}} {{.code_postal}} {{.adresse}}"
          ngram: 2
          threshold: 0.8
        expected: only-one  # Options: only-one, at-least-one, or many   
        header: true
        separator: ";"
        fieldsPerRecord: 0
        trim: true
```

In this example:

- The `jaccard` configuration uses the Jaccard similarity metric with `ngram: 2` and `threshold: 0.8`. This means that it will consider two-grams (pairs of consecutive characters) and look for a match with a similarity of at least 80%.

- The `csv` field represents the data in the CSV file, and the `entry` field represents the data in the JSON entry.

- The `expected` parameter is set to `at-least-one`, the mask will attempt to find the most similar result based on the Jaccard similarity metric and return at least one matching result. Adjust the ngram and threshold parameters based on your data characteristics and the level of similarity you want to consider.

This configuration allows for more flexibility in handling variations in the entry, such as differences in accents or letter case, by leveraging the Jaccard similarity metric. Adjust the `ngram` and `threshold` parameters based on the specific characteristics of your data and the level of similarity you want to consider.

## Performance 

If you want to first perform an exact match on the zip code (code_postal) and then apply Jaccard similarity for the address (adresse), you can configure it as follows:

```yaml

version: "1"
masking:
  - selector:
      jsonpath: "detaille_adresse"
    mask:
      findInCSV:
        uri: "path/to/your/file.csv"
        exactMatch:
          csv: "{{.code_postal}}"
          entry: "{{.code_postal}}"
        jaccard:
          csv: "{{.nom_commune}} {{.nom_voie}}"
          entry: "{{.nom_commune}} {{.adresse}}"
          ngram: 2
          threshold: 0.8
        expected: at-least-one  # Retrieve at least one result
        header: true
        separator: ";"
        fieldsPerRecord: 0
        trim: true
```

In this configuration:

- The `exactMatch` configuration is used first to filter the CSV data based on an exact match of the code_postal. This reduces the search space to only entries with the same zip code.

- The jaccard configuration is then applied to the filtered entries based on the adresse field, using the Jaccard similarity metric with a threshold of 0.8 and ngram set to 2.

- The `expected: at-least-one` parameter ensures that at least one matching result is retrieved.

This approach can significantly reduce the computational load when dealing with large CSV files by narrowing down the search to entries with the same zip code before applying the Jaccard similarity metric. Adjust the ngram and threshold parameters based on your specific requirements and characteristics of the data.
