### ISSUE TITLE
[Proposal] : New Feature XML Mask

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#272]
## Description of Need

I propose the addition of a new mask type to handle XML content within JSON values. Currently, PIMO supports various masks for JSON data, and this addition aims to extend its capabilities to include XML processing. The XML mask would allow users to target specific XML elements, attributes, and apply transformations using PIMO's masking syntax.

## Proposal

Mask Type: `xml`

- `xpath`: Specifies the XPath expression to target the XML element (only element name supported for V1).
- `injectParent` (optional): Injects the parent element into a variable for access in subsequent masks.
- `masking`: Sub-list of masks to be applied inside the selected XML element.

#### Input JSON:

```json
{
    "title": "my blog note",
    "content": "<note author='John Doe'><date>10/10/2023</date>This is a note of my blog....</note>"
}
```

#### Configuration:

```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "content"
    mask:
      xml:
        xpath: "note"
        injectParent: "_"
        masking:
          - selector:
              jsonpath: "@author"
            mask:
              template: "New Author Name"
```

#### Output JSON:

```json
{
    "title": "my blog note",
    "content": "<note author='New Author Name'><date>10/10/2023</date>This is a note of my blog....</note>"
}
```

#### Input JSON:

```json
{
    "title": "my blog note",
    "content": "<note><author>John Doe</author><date>10/10/2023</date>This is a note of my blog....</note>"
}
```

#### Configuration:

```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "content"
    mask:
      xml:
        xpath: "note"
        masking:
          - selector:
              jsonpath: "@author"
            mask:
              remove: true
```

#### Output JSON:

```json
{
    "title": "my blog note",
    "content": "<note><date>10/10/2023</date>This is a note of my blog....</note>"
}
```

## Additional Information

This feature enhances PIMO's capabilities by enabling users to manipulate XML content within JSON values. The proposed syntax aims to align with existing masking conventions for ease of use.
