### ISSUE TITLE
feat: timeline generation

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#292]
```yaml
  - selector:
      jsonpath: "timeline"
    mask:
      timeline:
        start: "now"
        format: "2006-01-02T15:04:05Z"
        points:
          - name: "birth" # without from by default this point is chosen relative to the start of the timeline
            min: "-P80Y"
            max: "-P18Y"
          - name: "contract"
            from: "birth" # contract point is located relatively to the "birth" point
            min: "+P18Y"
            max: "+P40Y"
            constraints:
              - before: "start"  # contract point should be before the starting point of the timeline
            when-invalid: "reject" # generate another timeline if constraint fails (other options : "null", "min-max")
          - name: "promotion"
            from: "contract" # promotion point is located relatively to the "contract" point
            min: "+P0"
            max: "+P5Y"
```

```json
{
  "timeline": {
    "start": "2024-04-02T16:37:11Z",
    "birth": "1969-07-14T21:18:37Z",
    "contract": "1995-02-01T00:36:30Z",
    "promotion": "1998-06-13T12:45:22Z"
  }
}
```
