### ISSUE TITLE
feat(ff1): preserve domain

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#304]
Parameter `preserve` of mask `ff1` should accept a list of character to preserve instead of preserving all characters outside the domain.

# Before 

```yaml
version: "1"
masking:

  - selector:
      jsonpath: "identifier"
    mask:
      ff1:
        domain: "0123456789"
        preserve: true
        keyFromEnv: "FF1_ENCRYPTION_KEY"
```

# After

```yaml
version: "1"
masking:

  - selector:
      jsonpath: "identifier"
    mask:
      ff1:
        domain: "0123456789"
        preserve: "-_." # only preserve these 3 characters, other characters outside of domain should trigger an error
        keyFromEnv: "FF1_ENCRYPTION_KEY"
```

For compatibility purpose, the first format of preserve should still be working.
