### ISSUE TITLE
feat(ff1): log field value as WARN when an error occurs

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#305]
FF1 mask will trigger an error in two cases :
- value to encrypt is too short (less than 2 characters)
- value to encrypt contains characters that are outside the domain, and not preserved

FF1 mask can catch errors with the `onError` parameter :

```yaml
version: "1"
masking:

  - selector:
      jsonpath: "identifier"
    mask:
      ff1:
        domain: "0123456789"
        onError: "{{.identifier}}" # value passthrough on error
        keyFromEnv: "FF1_ENCRYPTION_KEY"
```

If an error occurs and is catched by onError, then it should be logged in WARN level, for analysis purposes
