### ISSUE TITLE
feat(template): generate id sequence

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#306]
The requirement is to be able to generate an identifier in any format, with a varying part that can be incremented in sequence.

For example, an ID like : `ERR-0001` is an identifier that has the last 4 digits as varying part. The sequence generated should be : `ERR-0000`, `ERR-0001`, `ERR-0002`, `ERR-0003`, ..., `ERR-9999`.

The model of the generator can be :

```yaml
format: "ERR-0000"
varying: "0123456789"
```

Primarily this is intended to be used in templates, but this feature could also be used as a mask :

```yaml
version: "1"
masking:

  - selector:
      jsonpath: "identifier"
    mask:
      sequence:
        format: "ERR-0000"
        varying: "0123456789"
```
