### ISSUE TITLE
[PROPOSAL] Append the cache content file if the key does not exist

### ISSUE THREAD

**Issue by thierryprats** [CGI-FR/PIMO#315]
# Description

Execute ```pimo``` the flag ```--dump-cache cacheName=filename.json``` dumps cache content to a file.

The content of this file is overwritten each time the ```pimo``` command is executed with this flag.

# Demo

```data1.jsonl```

```json
{ "name" : "A" }
```

```data2.jsonl```

```json
{ "name" : "B" }
```

```masking.yml```

```yml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "name"
    mask:
      hashInUri: "pimo://nameFR"
    cache: "cacheName"

caches:
  cacheName:
    unique: true
```

Execute the ```pimo``` command with ```data1.jsonl``` :

```bash
pimo --dump-cache cacheName=cacheName.json < data1.jsonl
{"name":"Ursula"}
```

The ```cacheName.json``` content :

```json
{"key":"A","value":"Ursula"}
```

Execute the ```pimo``` command with ```data2.jsonl``` with the same cache file :

```bash
pimo --dump-cache cacheName=cacheName.json < data2.jsonl
{"name":"José"}
```

The ```cacheName.json``` content :

```json
{"key":"B","value":"José"}
```

# Proposal

Add the option to append the cache content file if the key does not exist.

Execute the ```pimo``` command with ```data1.jsonl``` :

```bash
pimo --dump-cache cacheName=cacheName.json < data1.jsonl
{"name":"Ursula"}
```

The ```cacheName.json``` content :

```json
{"key":"A","value":"Ursula"}
```

Execute the ```pimo``` command with ```data2.jsonl``` with the same cache file :

```bash
pimo --dump-cache cacheName=cacheName.json < data2.jsonl
{"name":"José"}
```

The ```cacheName.json``` content :

```json
{"key":"A","value":"Ursula"}
{"key":"B","value":"José"}
```
