### ISSUE TITLE
feat: preserve any value

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#320]
## Actual

```yaml
      masking:
        - selector:
            jsonpath: "name"
          mask:
            constant: "maskedName"
          preserve: "empty" # or "blank" or "null"
```

## Proposed

```yaml
      masking:
        - selector:
            jsonpath: "name"
          mask:
            constant: "maskedName"
          preserve: ["", null, "a_value_to_preserve"]
```
