### ISSUE TITLE
fix: timeline should not overwrite existing data

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#332]
Given masking.yaml

```yaml
version: "1"
masking:
  - selector:
      jsonpath: "timeline"
    masks:
      - add:
          departure: ""
          arrival: ""
          status: "COMPLETED"
      - timeline:
          format: "2006-01-02T15:04"
          start:
            name: "now"
          points:
            - name: "departure"
              min: "-P1Y"
              max: "P0"
            - name: "arrival"
              from: "departure"
              min: "P0"
              max: "PT10H"
```

## Expected

```json
{
  "timeline": {
    "now": "2024-09-19T17:34",
    "departure": "2024-05-07T11:23",
    "arrival": "2024-05-07T19:29",
    "status": "COMPLETED"
  }
}
```

## Actual

```json
{
  "timeline": {
    "now": "2024-09-19T17:34",
    "departure": "2024-05-07T11:23",
    "arrival": "2024-05-07T19:29"
  }
}
```
