### ISSUE TITLE
[PROPOSAL] [Draft] Start PIMO as web service mock

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#37]
# Start PIMO with a backend web service as source for mocks.

Related to #40 and #15 

Find a way to define routes. Possibly use the mmock project (https://github.com/jmartin82/mmock/)

**Comment by adrienaury** [comment]
## Drafts

```console
$ echo '{"userid": "6022955c5e70a4fbbd9fcfae"}' | pimo mock get https://www.data.gouv.fr/api/1/users/{{.userid}}/
{"about": null,"active": true,"avatar": null,"avatar_thumbnail": null,"email": null,"first_name": "coralie","id": "6022955c5e70a4fbbd9fcfae","last_name": "spillebout","metrics": {"datasets": 0,"followers": 0,"following": 0,"reuses": 0},"organizations": [],"page": "https://www.data.gouv.fr/fr/users/coralie-spillebout-1/","roles": [],"since": "2021-02-09T14:59:56.271000","slug": "coralie-spillebout-1","uri": "https://www.data.gouv.fr/api/1/users/coralie-spillebout-1/","website": null}
```

**Comment by adrienaury** [comment]
**`routes.yml`**
```yaml
version: "1"
routes:
- name: api/users/:{userid}/
  method: get
  maskingfile: masking-user.yml
```

**`masking-user.yml`**
```yaml
version: "1"
masking:
  - selector:
      jsonpath: "response.body.id"
    mask:
      add: "{{.params.url.userid}}"
  - selector:
      jsonpath: "response.body.name"
    masks:
      - add: "{{.params.url.userid}}"
      - hashInURI: "pimo://nameFR"
```

```console
$ pimo mock
```
