### ISSUE TITLE
feat: partition mask

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#382]
# 📝 Description

Add a new mask called **partition** to the masking.yml configuration file. This mask will allow handling fields containing different types of values by applying distinct transformations based on predefined conditions. A default option will handle unrecognized cases.

# 🎯 Problem to Solve

Currently, PIMO does not support processing fields with heterogeneous data types (e.g., technical identifiers and email addresses) conditionally. This limitation complicates the precise masking of sensitive data when a field contains mixed-value types.

# 🔍 Solution Details

The partition mask will rely on conditions to identify specific cases and apply a defined list of masks for each case. Example configuration:

```yaml
- selector:
    jsonpath: "ID"
  mask:
    partition:
      idrh:
        when: '{{ regexMatch "P[A-Z]{3}[0-9]{3}" .ID }}'
        then:
          # List of masks for the idrh case
      gag:
        when: '{{ regexMatch "GAG[0-9]{11}" .ID }}'
        then:
          # List of masks for the gag case
      default:
        then:
          # List of masks for unrecognized cases
```
