### ISSUE TITLE
feat: add mask match 

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#384]
# 📝 Description

Introduce a new mask called **match** to allow transformations on specific parts of a field's value. This mask will use regular expressions to capture subgroups and apply transformations to them individually.

# 🎯 Problem to Solve

Currently, PIMO lacks the capability to apply transformations to only specific segments of a field's value. This limitation is problematic when a value contains multiple components (e.g., letters and digits in a technical identifier) that require distinct masking strategies.

# 🔍 Solution Details

The match mask will:

Use a regular expression to capture subgroups within the value.
Apply a list of transformations (masks) to the captured subgroups.
Reconstruct the final value by replacing the matched parts with the transformed results.

Example configuration:

```yaml
- selector:
    jsonpath: "ID"
  mask:
    match:
      regex: "P(?P<letters>[A-Z]{3})(?P<digits>[0-9]{3})"
      replace:
        letters: # name of the captured group
        - ff1:
            keyFromEnv: ""
            domain: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"  # Transformation for the "letters" group
        digits:
        - ff1:
            keyFromEnv: ""
            domain: "0123456789"  # Transformation for the "digits" group
```
