### ISSUE TITLE
feat: log mask

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#388]
Create a new mask to output log

```yaml
log:
  message: '{{ .ID }}'
  level: "warn" # trace, debug, info, warn, error
```
