### ISSUE TITLE
feat: improve segments mask

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#389]
```yaml
      segments:
        regex: "^P(?P<letters>[A-Z]{3})(?P<digits>[0-9]{3})$"
        match: # replace renamed to match
          letters:
            - ff1:
                keyFromEnv: "FF1_ENCRYPTION_KEY"
                domain: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
          digits:
            - ff1:
                keyFromEnv: "FF1_ENCRYPTION_KEY"
                domain: "0123456789"
        nomatch: # add nomatch config
          - log:
              message: '{{ .ID }}'
              level: "warn"
```
