### ISSUE TITLE
[PROPOSAL] New mask : transcode

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#44]
# Transcode mask

A new mask that replace every character by a character of the another class.

By default, the following transcoding character classes are used 
- lowercase letters -> lowercase letters
- UPPERCASE LETTERS -> UPPERCASE LETTERS
- Digits -> Digits

## Example

```yaml
- selector:
    jsonpath: "id"
  mask:
    transcode: {}
```

```console
$ echo '{"id": "12345-ABCD-6789"}' | pimo
{"id": "30274-RPDM-2883"}
```

### Convert a hexadecimal values, by random hexadecimal values using only lowercase letters

```yaml
- selector:
    jsonpath: "id"
  mask:
    transcode:
      classes:
      - input: "0123456789abcdefABCDEF"
        output: "0123456789abcdef"
```

```console
$ echo '{"id": "1ef619-90F"}' | pimo
{"id": "d8e203-a92"}
```

### Mask some characters by a star

```yaml
- selector:
    jsonpath: "pseudo"
  mask:
    transcode:
      classes:
      - input: "abcdefghijklmnopqrstuvwxyz"
        output: "*"
```

```console
$ echo '{"pseudo": "mark_23"}' | pimo
{"id": "****_23"}
```
