### ISSUE TITLE
[PROPOSAL] Access to mask as template function

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#45]
```yaml
- selector:
    jsonpath: "surname"
  mask:
    template: '{{pimoHashInUri "pimo://nameFR"}}'
```

**Comment by youen** [comment]
`hashInUri` need original item to compute hash. So the right template should be.

```
- selector:
    jsonpath: "surname"
  mask:
    template: '{{pimoHashInUri .surname "pimo://nameFR"}}'
```
