### ISSUE TITLE
[PROPOSAL] Apply template on array

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#48]
## Input data

```json
{"array": ["value1", "value2", "value3"]}
```

## Expected output

```json
{"array": ["Value1", "Value2", "Value3"]}
```

## Problem

Existing masks don't work (`pipe`, `template`, ...)

```yaml
version: "1"
masking:
  - selector:
      jsonpath: "array"
    mask:
      pipe:
        masking:
          - selector:
              jsonpath: "."
            mask:
              template: "{{toUpper .}}"
```

The result is:

```
panic: interface conversion: interface {} is string, not model.Dictionary
```

**Comment by adrienaury** [comment]
```yaml
version: "1"
masking:
  - selector:
      jsonpath: "array"
    mask:
      template-each:
         item: "item"
         index: "index"
         template: "{{toUpper .item}}"
```
