### ISSUE TITLE
[PROPOSAL] From JSON mask

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#49]
A new mask that can convert an existing JSON string.

```yaml
- selector:
    jsonpath: "targetfield"
  mask:
    fromjson: "sourcefield"
```

## Examples

```console
$ echo '{"sourcefield": "null", "targetfield": ""}' | pimo
{"sourcefield": "null", "targetfield": null}
```

```console
$ echo '{"sourcefield": "1", "targetfield": ""}' | pimo
{"sourcefield": "1", "targetfield": 1}
```

```console
$ echo '{"sourcefield": "1.2", "targetfield": ""}' | pimo
{"sourcefield": "1.2", "targetfield": 1.2}
```

```console
$ echo '{"sourcefield": "{\"property\": \"hello\"}", "targetfield": ""}' | pimo
{"sourcefield": "{\"property\": \"hello\"}", "targetfield": {"property": "hello"}}
```
