### ISSUE TITLE
bug [randomChoice]  use differents seed for differents field

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#5]
Using this configuration 

```
version: "1"
seed: 3
masking:
  - selector:
      jsonpath: "name"
    mask:
      randomChoiceInUri: "file://../names.txt"
  - selector:
      jsonpath: "name2"
    mask:
      randomChoiceInUri: "file://../names.txt"
```

`name` and `name2` are always equal.
