### ISSUE TITLE
[bug] pipe mask after a fromjson mask yield a panic error

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#53]
With the following pipeline, pimo stop on panic error.

```yaml
# version du fichier de configuration PIMO
version: "1"
# Initialisation du générateur pseudo-aléatoire (optionel)
seed: 42
# Liste ordonnée des masque à appliquer
masking:
  - selector:
      jsonpath: "numberOfPet"
    mask:
      add: ""

  - selector:
      jsonpath: "numberOfPet"
    mask:
      randomInt:
        min: 4
        max: 10

  - selector:
      jsonpath: "fk_pets_owner_id"
    mask:
      add: ""
  - selector:
      jsonpath: "fk_pets_owner_id"
    mask:
      template: |
        [
          {{- range  $index := until (int .numberOfPet) -}}
            {{- if $index }},{{end -}}
            {
              "id": 7
            }
          {{- end -}}
        ]
  - selector:
      jsonpath: "fk_pets_owner_id"
    mask:
      fromjson: "fk_pets_owner_id"


  - selector:
      jsonpath: "fk_pets_owner_id"
    mask:
      pipe:
        masking:
          - selector:
              jsonpath: id
            mask:
              incremental:
                start: 1
                increment: 1
```

```console
❯ pimo --empty-input > with-pipe-result.json
panic: interface conversion: interface {} is map[string]interface {}, not model.Dictionary

goroutine 1 [running]:
github.com/cgi-fr/pimo/pkg/model.CleanDictionary(...)
        /workspace/pkg/model/ordered_dict.go:95
github.com/cgi-fr/pimo/pkg/model.CleanDictionarySlice(0x873720, 0xc00000ceb8, 0xc000024468, 0x10, 0xc0001e9dd8)
        /workspace/pkg/model/ordered_dict.go:104 +0x50c
github.com/cgi-fr/pimo/pkg/pipe.MaskEngine.MaskContext(0x0, 0x0, 0x9b0f10, 0xc000039540, 0x0, 0x0, 0x0, 0x0, 0xc00000cf00, 0xc000024468, ...)
        /workspace/pkg/pipe/pipe.go:69 +0x145
github.com/cgi-fr/pimo/pkg/model.(*MaskContextEngineProcess).ProcessDictionary.func2(0xc00000cf00, 0xc00000cf00, 0xc000024468, 0x10, 0x873720, 0xc00000ceb8, 0xc0001e9d58, 0xc00017b838, 0xc0001e9d40)
        /workspace/pkg/model/process_maskcontext.go:45 +0xb5
github.com/cgi-fr/pimo/pkg/model.selector.applyContext(0xc000024468, 0x10, 0x0, 0x0, 0xc00000cf00, 0xc00000cf00, 0x873720, 0xc00000ceb8, 0xc00000e480, 0x1, ...)
        /workspace/pkg/model/selector.go:203 +0x9c
github.com/cgi-fr/pimo/pkg/model.selector.applySubContext(0xc000024468, 0x10, 0x0, 0x0, 0xc00000cf00, 0xc00000cf00, 0xc00000e480, 0x1, 0x1, 0xc00000cf30)
        /workspace/pkg/model/selector.go:196 +0x339
github.com/cgi-fr/pimo/pkg/model.selector.ApplyContext(...)
        /workspace/pkg/model/selector.go:170
github.com/cgi-fr/pimo/pkg/model.(*MaskContextEngineProcess).ProcessDictionary(0xc0001db360, 0xc00000ced0, 0x9aa800, 0xc0001db380, 0x0, 0x0)
        /workspace/pkg/model/process_maskcontext.go:44 +0x1de
github.com/cgi-fr/pimo/pkg/model.(*ProcessPipeline).Next(0xc0000395c0, 0x0)
        /workspace/pkg/model/model.go:397 +0x96
github.com/cgi-fr/pimo/pkg/model.SimpleSinkedPipeline.Run(0x9b2a28, 0xc0000395c0, 0x9aeda0, 0xc0001db3a0, 0x0, 0x0)
        /workspace/pkg/model/model.go:445 +0x15f
main.run()
        /workspace/cmd/pimo/main.go:196 +0xba9
main.main.func1(0xc0001be280, 0xc0000694a0, 0x0, 0x1)
        /workspace/cmd/pimo/main.go:94 +0x25
github.com/spf13/cobra.(*Command).execute(0xc0001be280, 0xc00001e050, 0x1, 0x1, 0xc0001be280, 0xc00001e050)
        /home/vscode/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001be280, 0xc00017bf20, 0x1, 0x1)
        /home/vscode/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vscode/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /workspace/cmd/pimo/main.go:121 +0x713
```
