### ISSUE TITLE
[Proposal] new markov mask

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#54]
## Motivation

To generate random string the `regex` mask is limited for small text but can't generate pseudo natural language.

## Solution

Use markov chain [1] to produce pseudo text based on example. Add a new `markov` mask with transitions as parameters

```yaml

mask: 
  markov :
    # protection against infinity loop
    max-size: 20
    parameters:
       - from: "I am"
         to: "a"
         weight : 0.5
       - from: "I am"
         to: "not"
         weight : 0.5
       - from: "am a"
         to: "free"
         weight : 1
      - from: "free"
         to: "man"
         weight : 1

```

Parameters are extremely verbose and should not be compute by human. Parameters should be externalized in a json file.

```yaml
mask: 
  markov :
    # protection against infinity loop
    max-size: 20
    parameters: free-man.json
```

Or better compute from an sample text

```yaml
mask: 
  markov :
    # protection against infinity loop
    max-size: 20
    sample: free-man.txt
```

[1] https://en.wikipedia.org/wiki/Markov_chain#Markov_text_generators

**Comment by adrienaury** [comment]
Proposal : define default configuration accessible via pimo:// notation

```yaml
mask: 
  markov :
    max-size: 20
    parameters: pimo://markovFR
```
