### ISSUE TITLE
fromJson with integer or float value

### ISSUE THREAD

**Issue by RomandGuillaume** [CGI-FR/PIMO#55]
Following the purpose of this mask, i've tried the following :

```yaml
  - name: entry float value
    steps:
      - script: rm -rf masking.yml
      - script: |-
          cat > masking.yml <<EOF
          version: "1"
          masking:
            - selector:
                jsonpath: "targetfield"
              mask:
                fromjson: "sourcefield"
          EOF
          echo '{"sourcefield": "{\"property\":\"1.2\"}", "targetfield": ""}' | pimo
        assertions:
          - result.code ShouldEqual 0
          - result.systemout ShouldEqual {"sourcefield":"{\"property\":\"1.2\"}","targetfield":{"property":1.2}}
          - result.systemerr ShouldBeEmpty
```

In my comprehension of the mask, it should work this way but the targetfield property returns a string, not a float (works the same with integer)

**Comment by Baguettte** [comment]
IMO you ask the mask fromjson to transform the `sourcefield` into a json object (here a new dictionary). `targetfield.property` is independant so if you want to transform this field as well, you need to complete your masking configuration:

**masking.yml**
```yaml
version: "v1"
masking:
  - selector:
      jsonpath: "targetfield"
    mask:
      fromjson: "sourcefield"
  - selector:
      jsonpath: "targetfield.property"
    mask:
      fromjson: "targetfield.property"
```

However, executing this `echo '{"sourcefield": "{\"property\":\"1.2\"}", "targetfield": ""}' | pimo` ends in panic.

Might be solved with PR https://github.com/CGI-FR/PIMO/pull/88
