### ISSUE TITLE
[PROPOSAL] condition the execution of a mask for null or empty value

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#56]
## Problem

To preserve `null` or `""` values in the output we have to use a template mask with conditional test.

```yaml
  - selector:
      jsonpath: "comment"
    mask:
      template: |-
        {{if kindIs "string" .comment}}{{if eq "" .comment}}""{{else}}"Com_Fiche"{{end}}{{else}}null{{end}}
 ```

This kind of test is verbose and have to be repeat for each mask in the chain.

## Proposal

This is a proposal to add new attribute `preserve` in pipeline's step fill with one of options `"null"`, `"empty"`, `"blank"` (null or empty), `none` (default). 

The equivalent mask using the `preserve` feature is 

```yaml
  - selector:
      jsonpath: "comment"
    preserve: "blank"
    mask:
      template: "Com_Fiche"
```
