### ISSUE TITLE
[PROPOSAL] Templated uri for mask randomInUri

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#57]
## Problem 

Conditional random choice is not easy. All possibilities have to be choice and the template switch to the valid choice.

For example to choice name by gender :

```yaml
- selector:
      jsonpath: "name_F"
    mask:
      add : ""
- selector:
      jsonpath: "name_F"
    mask:
      randomChoiceInURI : "file://names_F.txt"
- selector:
      jsonpath: "name_M"
    mask:
      add : ""
- selector:
      jsonpath: "name_M"
    mask:
      randomChoiceInURI : "file://names_M.txt"
- selector:
      jsonpath: "name"
    mask:
      template: |-
        {{if .gender "F"}}{{.name_ F}}{{else}}{{.name_M}}{{end}}
# Remove temporaries fields
- selector:
      jsonpath: "name_F"
    mask:
      remove : true
- selector:
      jsonpath: "name_M"
    mask:
      remove : true
```

This is a pain for a two categories choice and is unusable for hundred categories choice.

## Solution

This issue propose to use template in uri path.

For example :

```yaml
- selector:
      jsonpath: "name"
    mask:
      randomChoiceInUri: "file://names_{{.gender}}.txt
```
