### ISSUE TITLE
[PROPOSAL] Luhn mask

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#61]
# Problem 

The [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm) is a simple checksum formula, used by french national bureau of statistics (INSEE).

When a [SIREN](https://en.wikipedia.org/wiki/SIREN_code) or SIRET code is anonymized, the last digit must be recalculated with the Luhn algorithm.

# Solution

```yaml
- selector:
    jsonpath: "siren"
  mask:
    # perform a luhn mod10 with the specified mapping on input string (char '0' = 0, char '1' = 1, ...)
    luhn:
      mod: 10
      map: "0123456789"
```

If `len(map)` != `mod` the mask will report a configuration error.

The previous example contains the default values for `mod` and `map` so it could be written as :

```yaml
- selector:
    jsonpath: "siren"
  mask:
    # perform a luhn mod10 on a numeric string
    luhn: {}
```

```console
$ echo '{"siren": "12345678"}' | pimo
{"siren": "123456782"}
```

**Comment by adrienaury** [comment]
Implementing #45 can lead to simpler configuration with complex anonymisation/pseudonymisation.

```yaml
- selector:
    jsonpath: "siren"
  mask:
    # keep first 2 digit then perform a luhn mod10 algorithm
    template: "luhn (substr 0 2 .siren) (substr 2 (len .siren) .siren)"
```
