### ISSUE TITLE
[bug] [fluxUri] Cannot use cache with mask fluxUri

### ISSUE THREAD

**Issue by Baguettte** [CGI-FR/PIMO#63]
With the following pipeline, pimo does not save ids in cache `cacheId`:
**masking.yml**
```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "ID"
    mask:
      fluxUri: "file://test-id.csv"
    cache: "cacheId"
caches:
  cacheId : {}
```
**test-id.csv**
```csv
1001
1002
1003
```
Executing pimo with this config, cacheIds.jsonl file is empty.
```console
$ pimo --dump-cache cacheId=cacheId.jsonl << EOF
> {"ID":1}
> {"ID":2}
> {"ID":3}
> EOF
{"ID":1001}
{"ID":1002}
{"ID":1003}
```

In comparaison using mask **randomChoiceInUri** saves ids just fine
