### ISSUE TITLE
[PROPOSAL] Randomize with custom seed

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#70]
# Problem

Sometimes, we need coherence in generated data (X always gives Y).
Using a randomization-based mask, such as `regex`, it's a difficult process that requires the use of `caches` and can be time/memory consuming.

# Solution

Add a parameter in the masking file to let the user force the value of seed used by RNG in the masks.

# Examples

```yaml
  - selector:
      jsonpath: "phone"
    seed:
      template: "{{.phone}}"
    mask:
      regex: "0[1-7]( ([0-9]){2}){4}"
```

```yaml
  - selector:
      jsonpath: "phone"
    seed:
      field: "phone"
    mask:
      regex: "0[1-7]( ([0-9]){2}){4}"
```
