### ISSUE TITLE
[PROPOSAL] multiple jsonpath in selector for same mask(s)

### ISSUE THREAD

**Issue by Baguettte** [CGI-FR/PIMO#71]
### Proposal
Possibility to enter a list of jsonpath in selectorType to apply the same mask to multiple fields:

**masking.yml**

```yaml
version: v1
  masking:
    - selector:
        jsonpaths:
          - name1
          - name2
          - name2
      mask:
        randomChoiceInUri: "pimo://nameFR"
```
Equivalent to: 
```yaml
version: v1
  masking:
    - selector:
        jsonpath: name1
      mask:
        randomChoiceInUri: "pimo://nameFR"
    - selector:
        jsonpath: name2
      mask:
        randomChoiceInUri: "pimo://nameFR"
    - selector:
        jsonpath: name3
      mask:
        randomChoiceInUri: "pimo://nameFR"
```
