### ISSUE TITLE
[PROPOSAL] option Preserve for fromCacheProcess

### ISSUE THREAD

**Issue by Baguettte** [CGI-FR/PIMO#83]
### Current situtation
FromCacheProcess presented in README.md
>If no matching is found in the cache, fromCache block the current line and the next lines are processing until a matching content go into the cache.

Sometimes we might want to preserve the current value if no match found (data structure manipulation use)

**masking.yml**
```yaml
version: 1
seed: 42
masking:
  - selector:
      jsonpath: id
    mask:
      fromCache: mycache
  - selector:
      jsonpath: name
    mask:
      randomChoiceInUri: "pimo://nameFR"
caches:
  mycache: {}
```
**data.jsonl**
```json
{"id":1,"name":"Pierre"}
{"id":2,"name":"Paul"}
{"id":3,"name":"Jacques"}
```
**cache.jsonl**
```json
{"key":1,"value":11}
{"key":3,"value":13}
```

```console
cat data.jsonl | pimo --load-cache mycache=cache.jsonl    
{"id":11,"name":"Rolande"}
{"id":13,"name":"Matéo"}
```

### Proposal

Using option `--preserve` (proposed in https://github.com/CGI-FR/PIMO/issues/56), we can notify the FromCacheProcess, and ignore the masking

**masking.yml**
```yaml
version: 1
seed: 42
masking:
  - selector:
      jsonpath: id
    mask:
      fromCache: mycache
    preserve: notInCache
  - selector:
      jsonpath: name
    mask:
      randomChoiceInUri: "pimo://nameFR"
caches:
  mycache: {}
```

```console
cat data.jsonl | pimo --load-cache mycache=cache.jsonl    
{"id":11,"name":"Rolande"}
{"id":2, "name":"Aaron"}
{"id":13,"name":"Matéo"}
```
