### ISSUE TITLE
[BUG] Mask Replacement does not work with nested selectors

### ISSUE THREAD

**Issue by Baguettte** [CGI-FR/PIMO#86]
### Problem
**input.jsonl**
```json
{"fk":{"name1":"Pierre","name2":"Paul"}}
```
**masking.yml**
```yaml
version: "v1"
masking:
  - selector:
      jsonpath: fk.name1
    mask:
      replacement: fk.name2
```

**expected_output.jsonl**
```json
{"fk":{"name1":"Paul","name2":"Paul"}}
```

**actual_output.jsonl**
```json
{"fk":{"name1":null,"name2":"Paul"}}
```

### Solution
Change this:
```go
type MaskEngine struct {
	Field string
}
```
Into this:
```go
type MaskEngine struct {
	Field model.Selector
}
```
