### ISSUE TITLE
bug: only first mask is processed with nested arrays

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/PIMO#9]
**data.jsonl**
```json
{"elements":[{"persons": [{"phonenumber": "027","email": "person@company.com"}]}]}
```

 **masking.yml**
```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "elements.persons.phonenumber"
    mask:
      regex: "0[1-7]( ([0-9]){2}){4}"
  - selector:
      jsonpath: "elements.persons.email"
    mask:
      regex: "[a-z]{10}@company\.com"
```

 **Result**
```json
{
  "elements": [
    {
      "persons": [
        {
          "email": "person@company.com",
          "phonenumber": "04 87 48 09 96"
        }
      ]
    }
  ]
}
```

 **Expected**
```json
{
  "elements": [
    {
      "persons": [
        {
          "email": "agcarobxcc@company.com",
          "phonenumber": "04 87 48 09 96"
        }
      ]
    }
  ]
}
```
