### ISSUE TITLE
[PROPOSAL] Reverse cache masking

### ISSUE THREAD

**Issue by youen** [CGI-FR/PIMO#96]
# Problem

Pimo is able to transpose original values to masked value using `cache` feature.

```yml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "category"
    mask:
      incremental:
        start: 1
        increment: 1
    # Optional cache (coherence preservation)
    cache: "cacheCategory"

caches:
  cacheCategory:
    # Optional bijective cache (enable re-identification if the cache is dumped on disk)
    unique: true
```

```
$ pimo --dump-cache cacheCategory=categoryCache.jsonl <<EOF
{ "category": "Animal" }
{ "category": "Food" }
{ "category": "IT" }
EOF
{ "category": 1 }
{ "category": 2 }
{ "category": 3 }
```

Pimo create a cache file `categoryCache.jsonl`

```
{ "Animal": 1 }
{ "Food": 2 }
{ "IT": 3 }
```

No documentation explain how to restore original data from masked data and cache file. 

```
{ "category": 1 }
{ "category": 2 }
{ "category": 3 }
```

**Comment by giraud10** [comment]
Cache file : 
```json
{"key":"Animal","value":1}
{"key":"Food","value":2}
{"key":"IT","value":3}
```

Reverse cache file using jq :
```console
< categoryCache.jsonl | jq '{"key": .value, "value": .key}' > categoryReverse.jsonl
```

Reverse cache file (`categoryReverse.jsonl`) :
```json
{"key": 1,"value": "Animal"}
{"key": 2,"value": "Food"}
{"key": 3,"value": "IT"}
```

`inverse.yml` file :
```yml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "category"
    mask:
      fromCache: "reverseCategory"
caches:
  reverseCategory:
    unique: true
```

```console
pimo --load-cache reverseCategory=categoryReverse.jsonl -c inverse.yml < data.json > dataOut.json
```

**Comment by adrienaury** [comment]
Proposal : option in cache

```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "category"
    mask:
      fromCache: "reverseCategory"
caches:
  reverseCategory:
    reverse: true
    unique: true
```

Proposal : option in fromCache mask

```yaml
version: "1"
seed: 42
masking:
  - selector:
      jsonpath: "category"
    mask:
      fromCache:
        cache: "category"
        reverse: true
caches:
  category:
    unique: true
```
